VTYS_Blog/VTYS_Blog/Models/LoginData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FireSharp;
using FireSharp.Response;
using FireSharp.Config;
using FireSharp.Interfaces;
using Newtonsoft.Json;



namespace VTYS_Blog.Models
{
    public class LoginData
    {
        public static IFirebaseConfig fc = new FirebaseConfig()
        {
            AuthSecret = "FG14qLcvzKH2pvA753I3t2NR9B2fImYjIxz1t2Ki",
            BasePath = "https://blogsayfasi-e8b92-default-rtdb.firebaseio.com/"
        };

        public IFirebaseClient client = new FireSharp.FirebaseClient(fc);

        public static void Kayıtol()
        {
           
        }

    }
}

VTYS_Blog/VTYS_Blog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VTYS_Blog.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VTYS_Blog/VTYS_Blog/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Firebase.Database;
using Firebase.Database.Query;
using System.Threading.Tasks;

namespace VTYS_Blog.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index() { return View(); }  


    }
}

VTYS_Blog/VTYS_Blog/Controllers/MainPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VTYS_Blog.Controllers
{
    public class MainPageController : Controller
    {
        // GET: MainPage
        public ActionResult Menu_Layout()
        {
            return View();
        }
        
        public ActionResult Anasayfa()
        {
            return View();
        }

        public ActionResult Blog()
        {
            return View();
        }

        public ActionResult İletişim()
        {
            return View();
        }

        public ActionResult Hakkımızda()
        {
            return View();
        }

        public ActionResult SatınAlma()
        {
            return View();
        }



    }
}

VTYS_Blog/VTYS_Blog/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VTYS_Blog/VTYS_Blog/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VTYS_Blog/VTYS_Blog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

VTYS_Blog/VTYS_Blog/Views/MainPage/Blog.cshtml
@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/MainPage/Menu_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<!-- body -->
<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="~/1forms/anasayfa/images/loading.gif" alt="" /></div>
    </div>
    <!-- end header -->
    <!-- revolution slider -->

    <div class="Blog-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="Blogheading">
                        <h3>Blog </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- section -->
    <div class="section layout_padding blog_blue_bg light_silver">
        <div class="container">

            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="full">
                        <div class="big_blog">
                            <img class="img-responsive" src="~/1forms/anasayfa/images/blog_1.png" alt="#" />
                        </div>
                        <div class="blog_cont_2">
                            <h3>Lorem ipsum dolor sit amet.</h3>
                            <p class="sublittle"> 19 Mart 2019  5 Okunma</p>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore sequi nesciunt, ea quisquam assumenda necessitatibus dolorum corporis libero iste vero.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end section -->
    <!-- section -->
    <section class="layout_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="heading" style="padding-left: 15px;padding-right: 15px;">
                        <h4 style="border-bottom: solid #333 1px;">Yorumlar / 2</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="full comment_blog_line">
                        <div class="row">
                            <div class="col-md-1">
                                <img src="~/1forms/anasayfa/images/c_1.png" alt="#" />
                            </div>
                            <div class="col-md-9">
                                <div class="full contact_text">
                                    <h3>Ali</h3>
                                    <h4>Posted on Jan 10 / 2017 at 06:53 am</h4>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet
                                        dolore magna aliquam erat volutpat.
                                    </p>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <a class="reply_bt" href="#">Cevapla</a>
                            </div>
                        </div>
                    </div>
                    <div class="full comment_blog_line">
                        <div class="row">
                            <div class="col-md-1">
                                <img src="~/1forms/anasayfa/images/c_2.png" alt="#" />
                            </div>
                            <div class="col-md-9">
                                <div class="full contact_text">
                                    <h3>Ayşe</h3>
                                    <h4>Yayınlandı Ocak 10 / 2017  06:53 </h4>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet
                                        dolore magna aliquam erat volutpat.
                                    </p>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <a class="reply_bt" href="#">Cevapla</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row margin_top_30">
                <div class="col-md-12 margin_top_30">
                    <div class="heading" style="padding-left: 15px;padding-right: 15px;">
                        <h4>Yorum Yapın</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="full comment_form">
                        <form action="index.html">
                            <fieldset>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <input type="text" name="name" placeholder="İsim" required="#" />
                                            <input type="email" name="email" placeholder="Email" required="#" />
                                        </div>
                                        <div class="col-md-6">
                                            <textarea placeholder="Yorum"></textarea>
                                        </div>
                                    </div>
                                    <div class="row margin_top_30">
                                        <div class="col-md-12">
                                            <div class="center">
                                                <button>Gönder</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end section -->
    <!-- footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <a href="#"><img src="" alt="#logo" /></a>
                    <ul class="contact_information">
                        <li><span><img src="~/1forms/anasayfa/images/location_icon.png" alt="#" /></span><span class="text_cont">Elazığ<br>Türkiye</span></li>
                        <li><span><img src="~/1forms/anasayfa/images/phone_icon.png" alt="#" /></span><span class="text_cont">000 000 000<br>507 654 3210</span></li>
                        <li><span><img src="~/1forms/anasayfa/images/mail_icon.png" alt="#" /></span><span class="text_cont">deneme@gmail.com<br>destek@gmail.com</span></li>
                    </ul>
                    <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6">
                    <div class="footer_links">
                        <h3>Hızlı Erişim</h3>
                        <ul>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Anasayfa</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Deneme link</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Deneme link</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Satın Alma</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Blog</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Deneme link</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Bize Ulaşın</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer_links">
                        <h3>Instagram</h3>
                        <ol>
                            <li><img class="img-responsive" src="" alt="#" /></li>
                            <li><img class="img-responsive" src="" alt="#" /></li>
                            <li><img class="img-responsive" src="" alt="#" /></li>
                            <li><img class="img-responsive" src="" alt="#" /></li>
                        </ol>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer_links">
                        <h3>Bize Ulaşın</h3>
                        <form action="index.html">
                            <fieldset>
                                <div class="field">
                                    <input type="text" name="name" placeholder="İsim" required="" />
                                </div>
                                <div class="field">
                                    <input type="email" name="email" placeholder="Email" required="" />
                                </div>
                                <div class="field">
                                    <input type="text" name="subject" placeholder="Konu" required="" />
                                </div>
                                <div class="field">
                                    <textarea placeholder="Mesajınız"></textarea>
                                </div>
                                <div class="field">
                                    <div class="center">
                                        <button class="reply_bt">Gönder</button>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </footer>

</body>
</html>

VTYS_Blog/VTYS_Blog/Views/MainPage/Hakkımızda.cshtml
@{
    ViewBag.Title = "Hakkımızda";
    Layout = "~/Views/MainPage/Menu_Layout.cshtml";
}

<h2>Hakkımızda</h2>

VTYS_Blog/VTYS_Blog/Views/MainPage/Menu_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>SPACE</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="~/1forms/anasayfa/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="~/1forms/anasayfa/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/1forms/anasayfa/css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="icon" type="~/1forms/anasayfa/image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/1forms/anasayfa/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->

</head>
<!-- body -->
<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="~/1forms/anasayfa/images/loading.gif" alt="" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
        <!-- header inner -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 logo_section">
                    <div class="full">
                        <div class="center-desk">
                            <div class="logo"> <a href="index.html"><img src="" alt="#logo"></a> </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="menu-area">
                        <div class="limit-box">
                            <nav class="main-menu">
                                <ul class="menu-area-main">
                                    <li>
                                        @*<a href="Anasayfa.html">Anasayfa</a>*@
                                        @Html.ActionLink("Anasayfa", "Anasayfa", "MainPage")
                                    </li>
                                    <li>
                                        @*<a href="about.html">Hakkımızda</a>*@
                                        @Html.ActionLink("Hakkımızda","Hakkımızda","MainPage")
                                    </li>
                                    <li>
                                        @*<a href="marketing.html">Satın Alma</a>*@
                                        @Html.ActionLink("Satın Alma","SatınAlma","MainPage")
                                    </li>
                                    <li>
                                        @*<a href="Blog.html">Blog</a>*@
                                        @Html.ActionLink("Blog","Blog", "MainPage")
                                    </li>
                                    <li>
                                        @*<a href="Iletisim.html">Bize Ulaşın</a>*@
                                        @Html.ActionLink("Bize Ulaşın","İletişim", "MainPage")
                                    </li>
                                    <a href="#"><img src="~/1forms/anasayfa/images/search_icon.png" alt="#" /></a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- end header inner -->
    </header>

    <script src="~/1forms/anasayfa/js/jquery.min.js"></script>
    <script src="~/1forms/anasayfa/js/popper.min.js"></script>
    <script src="~/1forms/anasayfa/js/bootstrap.bundle.min.js"></script>
    <script src="~/1forms/anasayfa/js/jquery-3.0.0.min.js"></script>
    <script src="~/1forms/anasayfa/js/plugin.js"></script>
    <!-- Scrollbar Js Files -->
    <script src="~/1forms/anasayfa/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/1forms/anasayfa/js/custom.js"></script>

    @RenderBody();
</body>
</html>

VTYS_Blog/VTYS_Blog/Views/MainPage/SatınAlma.cshtml
@{
    ViewBag.Title = "SatınAlma";
    Layout = "~/Views/MainPage/Menu_Layout.cshtml";
}

<h2>SatınAlma</h2>

VTYS_Blog/VTYS_Blog/Views/MainPage/İletişim.cshtml
@{
    ViewBag.Title = "İletişim";
    Layout = "~/Views/MainPage/Menu_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<!-- body -->
<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="~/1forms/anasayfa/images/loading.gif" alt="" /></div>
    </div>
    <!-- end loader -->
    
    <!-- end header -->
    <div class="contact-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="contactheading">
                        <h3>Bizimle İletişime Geçin</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- section -->
    <section class="layout_padding">
        <div class="container">



            <div class="row">
                <div class="col-md-12">
                    <div class="full comment_form">
                        <form action="index.html">
                            <fieldset>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <input type="text" name="name" placeholder="İsim" required="#" />
                                            <input type="email" name="email" placeholder="Email" required="#" />
                                            <input type="text" name="subject" placeholder="Konu" required="#" />
                                        </div>
                                        <div class="col-md-6">
                                            <textarea class="wdt" placeholder="Yorum"></textarea>
                                        </div>
                                    </div>
                                    <div class="row margin_top_30">
                                        <div class="col-md-12">
                                            <div class="center">
                                                <button>Gönder</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end section -->
    
    <!-- footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <a href="#"><img src="" alt="#logo" /></a>
                    <ul class="contact_information">
                        <li><span><img src="~/1forms/anasayfa/images/location_icon.png" alt="#" /></span><span class="text_cont">Elazığ<br>Türkiye</span></li>
                        <li><span><img src="~/1forms/anasayfa/images/phone_icon.png" alt="#" /></span><span class="text_cont">0312 255 5500<br>0(507) 789 7855</span></li>
                        <li><span><img src="~/1forms/anasayfa/images/mail_icon.png" alt="#" /></span><span class="text_cont">deneme@gmail.com<br>destek@gmail.com</span></li>
                    </ul>
                    <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6">
                    <div class="footer_links">
                        <h3>Hızlı Erişim</h3>
                        <ul>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Anasayfa</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Deneme link</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Deneme link</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Satın Alma</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Blog</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> Deneme link</a></li>
                            <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i> İletişim</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer_links">
                        <h3>Instagram</h3>
                        <ol>
                            <li><img class="img-responsive" src="" alt="#" /></li>
                            <li><img class="img-responsive" src="" alt="#" /></li>
                            <li><img class="img-responsive" src="" alt="#" /></li>
                            <li><img class="img-responsive" src="" alt="#" /></li>
                        </ol>
                    </div>
                </div>
                @*<div class="col-lg-3 col-md-6">
            <div class="footer_links">
                <h3>Bizimle İletişim Kurun</h3>
                <form action="index.html">
                    <fieldset>
                        <div class="field">
                            <input type="text" name="name" placeholder="İsim" required="" />
                        </div>
                        <div class="field">
                            <input type="email" name="email" placeholder="Email" required="" />
                        </div>
                        <div class="field">
                            <input type="text" name="subject" placeholder="Konu" required="" />
                        </div>
                        <div class="field">
                            <textarea placeholder="Mesaj"></textarea>
                        </div>
                        <div class="field">
                            <div class="center">
                                <button class="reply_bt">Gönder</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>*@
            </div>
        </div>
        </footer>
       

        <script>// This example adds a marker to indicate the position of Bondi Beach in Sydney,
      // Australia.
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 11,
          center: {lat: 40.645037, lng: -73.880224},
          });

        var image = '~/1forms/anasayfa/images/maps-and-flags.png';
        var beachMarker = new google.maps.Marker({
          position: {lat: 40.645037, lng: -73.880224},
          map: map,
          icon: image
        });
      }</script>

</body>
</html>

VTYS_Blog/VTYS_Blog/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
</head>
<body>
    <div> @RenderBody()
    </div>
</body>
</html>